### ISSUE TITLE
Total code coverage does not add up

### ISSUE THREAD

**Issue by HarelM** [OpenCoverUI/OpenCover.UI#108]
See picture below:
Coverage for all tests show 100% but the total is not (~97%)... am I missing something?
![image](https://cloud.githubusercontent.com/assets/3269297/12866099/d02a23fa-ccc9-11e5-9d79-f039c87ff59b.png)

**Comment by pver** [comment]
By default (because of legacy reasons) a class that has no coverage at all is filtered in the results. Probably this is what happens now in your example.

You can, however, display those as well by clicking the 'Show uncovered classes' button (this is the third button on top of the OpenCover results windows).

**Comment by pver** [comment]
@HarelM does the total add up with the entirely uncovered classes shown (see comment above to enable it)?

**Comment by HarelM** [comment]
Yes, it does add up.
BTW, When a writing a test that throws the coverage for this test is not full. Not sure where to open the issue about it...

**Comment by pver** [comment]
Probably @sawilde knows the specifics about how the coverage in that case is determined. But I think that's because when an exception is thrown, the test method is returning early, even when it's thrown from the last statement in your test method.

But I don't usually consider that as a problem for unit tests as long as the code under test itself is fully covered.

**Comment by pver** [comment]
Closing this one since it wasn't an issue (calculation includes uncovered classes)
