### ISSUE TITLE
Empty tree nodes and no title for coverage results

### ISSUE THREAD

**Issue by HarelM** [OpenCoverUI/OpenCover.UI#119]
I'm getting the following results:
![image](https://cloud.githubusercontent.com/assets/3269297/13539878/dcb4dd52-e25b-11e5-9837-7cf6111943e2.png)
As can be seen, some of the tree nodes are empty and all of them does not have a title - this makes me open each one to understand what ran in that node, needless to say this is not user friendly...

**Comment by pver** [comment]
This is fixed in #114 and will be in the next release.

As a temporary workaround until the new release, you could use an older version of OpenCover (OpenCover itself, not OpenCover.UI), because this problem was introduced because of recent changes in OpenCover (see #114 for details). I think it was introduced after OpenCover 4.6.434 or 4.6.476, so with those versions the assembly names are still visible.
