### ISSUE TITLE
Beautify line coverage

### ISSUE THREAD

**Issue by twenzel** [OpenCoverUI/OpenCover.UI#43]
At the moment the line coverage is shown via a colored background for the whole line.

![today](https://cloud.githubusercontent.com/assets/1618378/6186805/e2a0569a-b37e-11e4-9196-841214a5710a.png)

I think we should change this to a __less invasive__ way. Like:

![ncrunch](http://www.ncrunch.net/Content/Home/featureCodeCoverage.png)

**Comment by pver** [comment]
:+1: 
Looks great indeed!
It may be less visible for partially covered lines (for instance parts of an if statement), but a solution could be to give such a line an orange bullet. 
And we could even make the bullet clickable, so that when the user clicks it (or hovers over it) we still show the current style of background color for the corresponding line

**Comment by twenzel** [comment]
@sawilde you can assign this to me if you like.

**Comment by sawilde** [comment]
we have to be mindful of how we do things as I see you have posted an ncrunch screen shot - I do like the suggestion by @pver as it allows both options - less invasive but a switch to detailed when needed.
