### ISSUE TITLE
VS2013 build

### ISSUE THREAD

**Issue by bigmat** [OpenCoverUI/OpenCover.UI#83]
I can't open the project in VS2013, i have an error message saying that "	OpenCover.UI\OpenCover.UI.VS2013.csproj: The application which this project type is based on was not found."
Can someone help please ?

**Comment by sawilde** [comment]
You need to install more *stuff* in order to compile.

This stack overflow post describes the issue - http://stackoverflow.com/questions/26297014/visual-studio-doesnt-support-specific-csproj-file

The project type guids are listed here (may become out of date) - http://www.mztools.com/articles/2008/mz2008017.aspx

Looking at https://github.com/OpenCoverUI/OpenCover.UI/blob/master/OpenCover.UI/OpenCover.UI.VS2013.csproj#L21 we see that

82b43b9b-a64c-4715-b499-d71e9ca2bd60 - Extensibility 
60dc8134-eba5-43b8-bcc9-bb4bc16c2548 - WPF
FAE04EC0-301F-11D3-BF4B-00C04F79EFBC - C#

Out of these I suspect you are missing **Extensibility** which you will need to install.

**Comment by pver** [comment]
As Shaun mentions, you need to install some extra compared to a regular Visual Studio setup: the Visual Studio SDK. 
The installer for the Visual Studio 2013 SDK, can be found here: http://www.microsoft.com/en-us/download/details.aspx?id=40758. After installing the SDK, you should be able to open and run the solution

**Comment by bigmat** [comment]
Yes it's working thx !
I will look how i can fix the issue i have with my project, there are a lot of unit tests and the plugin worked only the first tie i installed it, now it does not find any tests. with the source i can debug

**Comment by pver** [comment]
:+1: thank you too for helping :) Keep us posted if you find anything or feel free to create a ticket with specifics on the issue(s) you run into
