### ISSUE TITLE
nunit 3 support

### ISSUE THREAD

**Issue by jmecosta** [OpenCoverUI/OpenCover.UI#97]
hi,

do you have already this somewhere?

br,
jc

**Comment by pver** [comment]
Hi,

I don't think anyone is working on that already, but I think we definitely should support this in the near future. I'm not sure yet if we should make a (temporary) separate version for this, since NUnit 3 is still in beta. It will probably depend on how we can combine NUnit 2 and NUnit 3 support in the plugin.

Adding NUnit 3 support shouldn't take too much work though, because they now provide a public API to do test discovery (NUnit test discovery is now implemented in OpenCover.UI itself).

**Comment by jmecosta** [comment]
i have patched the tool and the only thing needed was to modify the command line parameters to nunit, / instead of --... its good for us for now, but best option is to use the nunit api for sure. supose this is what you are after: https://github.com/nunit/nunit3-vs-adapter/blob/master/src/NUnitTestAdapter/NUnit3TestDiscoverer.cs

**Comment by jmecosta** [comment]
But I suppose you know that already :)

**Comment by glen-nicol** [comment]
Has any progress been made on this? I don't mind doing some work to get it going. My main question is what is wrong though? Mine discovers Nunit3 tests but when I point it to the nunit3-console.exe it throws a NullReferenceException in a dialog.

**Comment by bunnu** [comment]
I created a pull request for adding NUnit 3.x support. Take a look at #102

**Comment by pver** [comment]
Pulled in #102
